
version: '3'

services:

  frontend:

    image: jagadishspyd/e-education:1.0

    container_name: educationfront

    ports:

      - "3000:80"  # Map host port 3000 to container port 80

    networks:

      - my-network

    environment:

      - API_BASE_URL=http://13.126.181.47:8082
 
  backend:

    image: jagadishspyd/e-education:1.0BE

    container_name: educationback

    ports:

      - "8082:8082"

    networks:

      - my-network
 
  reverse-proxy:

    image: nginx:latest

    ports:

      - "8443:443"  # Map host port 8443 to container port 443 (HTTPS)

      - "8081:80"   # Map host port 8080 to container port 80 (HTTP)

    volumes:

      - ./nginx.conf:/etc/nginx/nginx.conf

      - ./ssl:/etc/nginx/ssl

    networks:

      - my-network

    depends_on:

      - frontend

      - backend
 

 
 
networks:
  my-network:
    driver: bridge
