version: '3'
services:
  frontend:
    image: jagadishspyd/e-education:1.0  # Frontend image
    container_name: educationfront  # Custom container name for frontend
    ports:
      - "80:80"  # Frontend exposed on port 80
    networks:
      - my-network
    environment:
      - API_BASE_URL=http://13.126.181.47:8082  # Frontend points to the backend via the domain
 
  backend:
    image: jagadishspyd/e-education:1.0BE  # Backend image
    container_name: educationback  # Custom container name for backend
    ports:
      - "8082:8082"  # Backend exposed on port 8082
    networks:
      - my-network
 
  reverse-proxy:
    image: nginx:latest
    ports:
      - "443:443"  # HTTPS
      - "80:80"     # HTTP (optional, for redirecting to HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx configuration
      - ./ssl:/etc/nginx/ssl  # Mount SSL certificates
    networks:
      - my-network
    depends_on:
      - frontend
      - backend
 
networks:
  my-network:
    driver: bridge
