apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
  namespace: e-education-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  selector:
    app: java-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
