# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
  namespace: e-education-backend
spec:
  selector:
    app: java-backend
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 8082  # Matches container port
  type: ClusterIP
